export const COUNTRY_CODE: { [key: string]: { kor: string; eng: string } } = {
  AD: { kor: "안도라", eng: "ANDORRA" },
  AE: { kor: "아랍에미리트", eng: "UNITED ARAB EMIRATES" },
  AF: { kor: "아프가니스탄", eng: "AFGHANISTAN" },
  AG: { kor: "안티구아 바부다", eng: "ANTIGUA AND BARBUDA" },
  AI: { kor: "앙길라", eng: "ANGUILLA" },
  AL: { kor: "알바니아", eng: "ALBANIA" },
  AM: { kor: "아르메니아", eng: "ARMENIA" },
  AN: { kor: "네덜란드령 안틸레스", eng: "NETHERLANDS ANTILLES" },
  AO: { kor: "앙골라", eng: "ANGOLA" },
  AQ: { kor: "남극", eng: "ANTARCTICA" },
  AR: { kor: "아르헨티나", eng: "ARGENTINA" },
  AS: { kor: "아메리칸 사모아", eng: "AMERICAN SAMOA" },
  AT: { kor: "오스트리아", eng: "AUSTRIA" },
  AU: { kor: "호주", eng: "AUSTRALIA" },
  AW: { kor: "아루바", eng: "ARUBA" },
  AX: { kor: "알랜드 군도", eng: "ALAND ISLANDS" },
  AZ: { kor: "아제르바이잔", eng: "AZERBAIJAN" },
  BA: { kor: "보스니아 헤르체고비나", eng: "BOSNIA HERCEGOVINA" },
  BB: { kor: "바베이도스", eng: "BARBADOS" },
  BD: { kor: "방글라데시", eng: "BANGLADESH" },
  BE: { kor: "벨기에", eng: "BELGIUM" },
  BF: { kor: "부르키나파소", eng: "BURKINA FASO" },
  BG: { kor: "불가리아", eng: "BULGARIA" },
  BH: { kor: "바레인", eng: "BAHRAIN" },
  BI: { kor: "부룬디", eng: "BURUNDI" },
  BJ: { kor: "베냉", eng: "BENIN" },
  BL: { kor: "세인트 바르탤르미", eng: "SAINT BARTHELEMY" },
  BM: { kor: "버뮤다", eng: "BERMUDA" },
  BN: { kor: "브루나이", eng: "BRUNEI DARUSSALAM" },
  BO: { kor: "볼리비아", eng: "BOLIVIA" },
  BQ: { kor: "보네르", eng: "BONAIRE" },
  BR: { kor: "브라질", eng: "BRAZIL" },
  BS: { kor: "바하마", eng: "BAHAMAS" },
  BT: { kor: "부탄", eng: "BHUTAN" },
  BV: { kor: "부베섬", eng: "BOUVET ISLAND" },
  BW: { kor: "보츠와나", eng: "BOTSWANA" },
  BY: { kor: "벨라루스", eng: "BELARUS" },
  BZ: { kor: "벨리즈", eng: "BELIZE" },
  CA: { kor: "캐나다", eng: "CANADA" },
  CC: { kor: "코코스 제도", eng: "COCOS (KEELING) ISLANDS" },
  CD: { kor: "콩고민주공화국", eng: "Democratic Republic of the Congo" },
  CF: { kor: "중앙아프리카공화국", eng: "CENTRAL AFRICAN REPUBLIC" },
  CG: { kor: "콩고", eng: "CONGO" },
  CH: { kor: "스위스", eng: "SWITZERLAND" },
  CI: { kor: "코트디부아르", eng: "COTE D`IVOIRE" },
  CK: { kor: "쿡 제도", eng: "COOK ISLANDS" },
  CL: { kor: "칠레", eng: "CHILE" },
  CM: { kor: "카메룬", eng: "CAMEROON" },
  CN: { kor: "중국", eng: "CHINA" },
  CO: { kor: "콜롬비아", eng: "COLOMBIA" },
  CR: { kor: "코스타리카", eng: "COSTA RICA" },
  CU: { kor: "쿠바", eng: "CUBA" },
  CV: { kor: "카보베르데", eng: "CAPE VERDE" },
  CW: { kor: "퀴라소", eng: "CURACAO" },
  CX: { kor: "크리스마스섬", eng: "CHRISTMAS ISLAND" },
  CY: { kor: "사이프러스", eng: "CYPRUS" },
  CZ: { kor: "체코공화국", eng: "CZECH REPUBLIC" },
  DE: { kor: "독일", eng: "GERMANY" },
  DJ: { kor: "지부티", eng: "DJIBOUTI" },
  DK: { kor: "덴마크", eng: "DENMARK" },
  DM: { kor: "도미니카", eng: "DOMINICA" },
  DO: { kor: "도미니카 공화국", eng: "DOMINICAN REPUBLIC" },
  DZ: { kor: "알제리", eng: "ALGERIA" },
  EC: { kor: "에쿠아도르", eng: "ECUADOR" },
  EE: { kor: "에스토니아", eng: "ESTONIA" },
  EG: { kor: "이집트", eng: "EGYPT" },
  EH: { kor: "서사하라", eng: "WESTERN SAHARA" },
  ER: { kor: "에리트레아", eng: "ERITREA" },
  ES: { kor: "스페인", eng: "SPAIN" },
  ET: { kor: "이디오피아", eng: "ETHIOPIA" },
  FI: { kor: "핀란드", eng: "FINLAND" },
  FJ: { kor: "피지", eng: "FIJI" },
  FK: { kor: "포클랜드섬", eng: "FALKLAND ISLANDS" },
  FM: { kor: "미크로네시아", eng: "MICRONESIA" },
  FO: { kor: "페로 군도", eng: "FAROE ISLANDS" },
  FR: { kor: "프랑스", eng: "FRANCE" },
  GA: { kor: "가봉", eng: "GABON" },
  GB: { kor: "영국", eng: "UNITED KINGDOM" },
  GD: { kor: "그레나다", eng: "GRENADA" },
  GE: { kor: "조지아", eng: "GEORGIA" },
  GF: { kor: "프랑스령 기아나", eng: "FRENCH GUIANA" },
  GG: { kor: "건지", eng: "GUERNSEY" },
  GH: { kor: "가나", eng: "GHANA" },
  GI: { kor: "지브랄타", eng: "GIBRALTAR" },
  GL: { kor: "그린랜드", eng: "GREENLAND" },
  GM: { kor: "감비아", eng: "GAMBIA" },
  GN: { kor: "기니", eng: "GUINEA" },
  GP: { kor: "과들루프", eng: "GUADELOUPE" },
  GQ: { kor: "적도 기니", eng: "EQUATORIAL GUINEA" },
  GR: { kor: "그리스", eng: "GREECE" },
  GS: {
    kor: "사우스조지아 사우스샌드위치 제도",
    eng: "SOUTH GEORGIA AND SOUTH SANDWICH LSLANDS",
  },
  GT: { kor: "과테말라", eng: "GUATEMALA" },
  GU: { kor: "괌", eng: "GUAM" },
  GW: { kor: "기네비쏘", eng: "GUINEA-BISSAU" },
  GY: { kor: "가이아나", eng: "GUYANA" },
  HK: { kor: "홍콩", eng: "HONG KONG" },
  HM: { kor: "허드 맥도날드 군도", eng: "HEARD AND MCDONALD ISLANDS" },
  HN: { kor: "온두라스", eng: "HONDURAS" },
  HR: { kor: "크로아티아", eng: "CROATIA" },
  HT: { kor: "아이티", eng: "HAITI" },
  HU: { kor: "헝가리", eng: "HUNGARY" },
  HW: { kor: "하와이", eng: "HAWAII" },
  ID: { kor: "인도네시아", eng: "INDONESIA" },
  IE: { kor: "아일랜드", eng: "IRELAND" },
  IL: { kor: "이스라엘", eng: "ISRAEL" },
  IM: { kor: "맨섬", eng: "ISLE OF MAN" },
  IN: { kor: "인도", eng: "INDIA" },
  IO: { kor: "영인도 제도", eng: "BRITISH INDIAN OCEAN TERRITORY" },
  IQ: { kor: "이라크", eng: "IRAQ" },
  IR: { kor: "이란", eng: "IRAN" },
  IS: { kor: "아이슬랜드", eng: "ICELAND" },
  IT: { kor: "이탈리아", eng: "ITALY" },
  JE: { kor: "저지", eng: "JERSEY" },
  JM: { kor: "자메이카", eng: "JAMAICA" },
  JO: { kor: "요르단", eng: "JORDAN" },
  JP: { kor: "일본", eng: "JAPAN" },
  KE: { kor: "케냐", eng: "KENYA" },
  KG: { kor: "키르기스스탄", eng: "KYRGYZSTAN" },
  KH: { kor: "캄보디아", eng: "CAMBODIA" },
  KI: { kor: "키리바시", eng: "KIRIBATI" },
  KM: { kor: "코모르", eng: "COMOROS" },
  KN: { kor: "세인트 키츠 네비스", eng: "SAINT KITTS AND NEVIS" },
  KP: { kor: "북한", eng: "NORTH KOREA" },
  KR: { kor: "대한민국", eng: "KOREA" },
  KV: { kor: "코소보", eng: "KOSOVO" },
  KW: { kor: "쿠웨이트", eng: "KUWAIT" },
  KY: { kor: "케이맨섬", eng: "CAYMAN ISLANDS" },
  KZ: { kor: "카자흐스탄", eng: "KAZAKHSTAN" },
  LA: { kor: "라오스", eng: "LAOS" },
  LB: { kor: "레바논", eng: "LEBANON" },
  LC: { kor: "세인트 루시아", eng: "SAINT LUCIA" },
  LI: { kor: "리히텐슈타인", eng: "LIECHTENSTEIN" },
  LK: { kor: "스리랑카", eng: "SRI LANKA" },
  LR: { kor: "라이베리아", eng: "LIBERIA" },
  LS: { kor: "레소토", eng: "LESOTHO" },
  LT: { kor: "리투아니아", eng: "LITHUANIA" },
  LU: { kor: "룩셈부르크", eng: "LUXEMBOURG" },
  LV: { kor: "라트비아", eng: "LATVIA" },
  LY: { kor: "리비아", eng: "LIBYAN ARAB JAMAHIRIYA" },
  MA: { kor: "모로코", eng: "MOROCCO" },
  MC: { kor: "모나코", eng: "MONACO" },
  MD: { kor: "몰도바", eng: "MOLDOVA" },
  ME: { kor: "몬테네그로", eng: "MONTENEGRO" },
  MF: { kor: "세인트 마틴", eng: "SAINT MARTIN (FRENCH PART)" },
  MG: { kor: "마다가스카르", eng: "MADAGASCAR" },
  MH: { kor: "마샬군도", eng: "MARSHALL ISLANDS" },
  MK: { kor: "마케도니아", eng: "MACEDONIA" },
  ML: { kor: "말리", eng: "MALI" },
  MM: { kor: "미얀마", eng: "MYANMAR" },
  MN: { kor: "몽골", eng: "MONGOLIA" },
  MO: { kor: "마카오", eng: "MACAU" },
  MP: { kor: "북마리아나 군도", eng: "NORTHERN MARIANA ISLANDS" },
  MQ: { kor: "마르티니크", eng: "MARTINIQUE" },
  MR: { kor: "모리타니", eng: "MAURITANIA" },
  MS: { kor: "몬트세라트", eng: "MONTSERRAT" },
  MT: { kor: "말타", eng: "MALTA" },
  MU: { kor: "모리셔스", eng: "MAURITIUS" },
  MV: { kor: "몰디브", eng: "MALDIVES" },
  MW: { kor: "말라위", eng: "MALAWI" },
  MX: { kor: "멕시코", eng: "MEXICO" },
  MY: { kor: "말레이시아", eng: "MALAYSIA" },
  MZ: { kor: "모잠비크", eng: "MOZAMBIQUE" },
  NA: { kor: "나미비아", eng: "NAMIBIA" },
  NC: { kor: "뉴칼레도니아", eng: "NEW CALEDONIA" },
  NE: { kor: "니제르", eng: "NIGER" },
  NF: { kor: "노퍽섬", eng: "NORFOLK ISLAND" },
  NG: { kor: "나이지리아", eng: "NIGERIA" },
  NI: { kor: "니카라과", eng: "NICARAGUA" },
  NL: { kor: "네덜란드", eng: "NETHERLANDS" },
  NO: { kor: "노르웨이", eng: "NORWAY" },
  NP: { kor: "네팔", eng: "NEPAL" },
  NR: { kor: "나우루", eng: "NAURU" },
  NT: { kor: "중립지대", eng: "NEUTRAL ZONE" },
  NU: { kor: "니우에", eng: "NIUE" },
  NZ: { kor: "뉴질랜드", eng: "NEW ZEALAND" },
  OM: { kor: "오만", eng: "OMAN" },
  PA: { kor: "파나마", eng: "PANAMA" },
  PE: { kor: "페루", eng: "PERU" },
  PF: { kor: "프랑스령 폴리네시아", eng: "FRENCH POLYNESIA" },
  PG: { kor: "파푸아뉴기니", eng: "PAPUA NEW GUINEA" },
  PH: { kor: "필리핀", eng: "PHILIPPINES" },
  PK: { kor: "파키스탄", eng: "PAKISTAN" },
  PL: { kor: "폴란드", eng: "POLAND" },
  PM: { kor: "세인트 피에르 미?론", eng: "SAINT PIERRE AND MIQUELON" },
  PN: { kor: "핏케언 군도", eng: "PITCAIRN" },
  PR: { kor: "푸에르토리코", eng: "PUERTO RICO" },
  PS: { kor: "팔레스타인", eng: "PALESTINE" },
  PT: { kor: "포르투갈", eng: "PORTUGAL" },
  PW: { kor: "팔라우", eng: "PALAU" },
  PY: { kor: "파라과이", eng: "PARAGUAY" },
  QA: { kor: "카타르", eng: "QATAR" },
  RE: { kor: "리유니언", eng: "REUNION" },
  RO: { kor: "루마니아", eng: "ROMANIA" },
  RS: { kor: "세르비아", eng: "SERBIA" },
  RU: { kor: "러시아", eng: "RUSSIAN FEDERATION" },
  RW: { kor: "르완다", eng: "RWANDA" },
  SA: { kor: "사우디아라비아", eng: "SAUDI ARABIA" },
  SB: { kor: "솔로몬 군도", eng: "SOLOMON ISLANDS" },
  SC: { kor: "세이셸", eng: "SEYCHELLES" },
  SD: { kor: "수단", eng: "SUDAN" },
  SE: { kor: "스웨덴", eng: "SWEDEN" },
  SG: { kor: "싱가포르", eng: "SINGAPORE" },
  SH: { kor: "세인트 헬레나", eng: "SAINT HELENA" },
  SI: { kor: "슬로베니아", eng: "SLOVENIA" },
  SJ: {
    kor: "스발바르드 얀마이엔 제도",
    eng: "SVALBARD AND JAN MAYEN ISLANDS",
  },
  SK: { kor: "슬로바키아", eng: "SLOVAKIA" },
  SL: { kor: "시에라리온", eng: "SIERRA LEONE" },
  SM: { kor: "산마리노", eng: "SAN MARINO" },
  SN: { kor: "세네갈", eng: "SENEGAL" },
  SO: { kor: "소말리아", eng: "SOMALIA" },
  SR: { kor: "수리남", eng: "SURINAME" },
  SS: { kor: "남수단", eng: "SOUTH SUDAN" },
  ST: { kor: "쌍투메 프린시페", eng: "SAO TOME AND PRINCIPE" },
  SV: { kor: "엘살바도르", eng: "EL SALVADOR" },
  SX: { kor: "신트마르텐", eng: "SINT MAARTEN (DUTCH PART)" },
  SY: { kor: "시리아", eng: "SYRIAN ARAB REPUBLIC" },
  SZ: { kor: "스와질랜드", eng: "SWAZILAND" },
  TC: { kor: "터크스 카이코스 제도", eng: "TURKS AND CAICOS ISLANDS" },
  TD: { kor: "차드", eng: "CHAD" },
  TF: { kor: "프랑스 남부지역", eng: "FRENCH SOUTHERN TERRITORIES" },
  TG: { kor: "토고", eng: "TOGO" },
  TH: { kor: "태국", eng: "THAILAND" },
  TJ: { kor: "타지키스탄", eng: "TAJIKISTAN" },
  TK: { kor: "토켈라우", eng: "TOKELAU" },
  TL: { kor: "동티모르", eng: "EAST TIMOR" },
  TM: { kor: "투르크메니스탄", eng: "TURKMENISTAN" },
  TN: { kor: "튀니지", eng: "TUNISIA" },
  TO: { kor: "통가", eng: "TONGA" },
  TR: { kor: "튀르키예", eng: "TURKIYE" },
  TT: { kor: "트리니다드토바고", eng: "TRINIDAD AND TOBAGO" },
  TV: { kor: "투발루", eng: "TUVALU" },
  TW: { kor: "대만", eng: "TAIWAN" },
  TZ: { kor: "탄자니아", eng: "TANZANIA" },
  UA: { kor: "우크라이나", eng: "UKRAINE" },
  UG: { kor: "우간다", eng: "UGANDA" },
  UM: { kor: "미국령 소군도", eng: "UNITED STATES MINOR OUTLYING ISLANDS" },
  US: { kor: "미국", eng: "UNITED STATES" },
  UY: { kor: "우루과이", eng: "URUGUAY" },
  UZ: { kor: "우즈베키스탄", eng: "UZBEKISTAN" },
  VA: { kor: "바티칸", eng: "VATICAN CITY STATE" },
  VC: {
    kor: "세인트 빈센트 그레나딘스",
    eng: "SAINT VINCENT AND THE GRENADINES",
  },
  VE: { kor: "베네수엘라", eng: "VENEZUELA" },
  VG: { kor: "영국령 버진아일랜드", eng: "VIRGIN ISLANDS (BRITISH)" },
  VI: { kor: "미국령 버진아일랜드", eng: "VIRGIN ISLANDS (U.S.)" },
  VN: { kor: "베트남", eng: "VIET NAM" },
  VU: { kor: "바누아투", eng: "VANUATU" },
  WF: { kor: "월리스 후트나", eng: "WALLIS AND FUTUNA ISLANDS" },
  WS: { kor: "사모아", eng: "SAMOA" },
  YE: { kor: "예멘", eng: "YEMEN" },
  YT: { kor: "마요트", eng: "MAYOTTE" },
  YU: { kor: "유고슬라비아", eng: "YUGOSLAVIA" },
  ZA: { kor: "남아프리카공화국", eng: "SOUTH AFRICA" },
  ZM: { kor: "잠비아", eng: "ZAMBIA" },
  ZR: { kor: "자이르", eng: "ZAIRE" },
  ZW: { kor: "짐바브웨", eng: "ZIMBABWE" },
  ZZ: { kor: "국적불명", eng: "UNKNOWN" },
};
